# Site settings
title: "Govind Tank Resume"
description: "A resume template of govind tank."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Govind S. Tank"
resume_title:                   "Android Application Developer"
resume_contact_email:           "govindtank600@gmail.com"
resume_contact_telephone:       "(+91) 84604 84061"
resume_contact_address:         "59/264, Shreenagar Society, Sector 24, Gandhinagar, Gujarat-382024"
resume_header_contact_info: "Gandhinagar, Gujarat | (+91) 84604 84061 | govindtank600@gmail.com"
resume_header_intro: "<p> I work as a freelancer cum consultant for mobile application development. I have tried my hands on designing and developing mobile and web applications using various programming languages like; Java, Kotlin, Objective-C, C++. Also have experience building desktop application with .NET technology. I have tried my skills in building complete mobile applicaions from system-requirement generation, prototyping, designing, coding, deplyoing.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/govindtank/"
  resume_twitter_url:           "http://twitter.com/govindtank4"
 # resume_dribbble_url:          "https://dribbble.com/govindtank"
  resume_facebook_url:          "https://facebook.com/govind.tank.77"
  resume_linkedin_url:          "https://www.linkedin.com/in/govindtank"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://govindtank.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
